allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  bufferutil: set this to true or false
  core-js: true
  esbuild: true
  prisma: true
  svelte-preprocess: true
  svelte-query-params: set this to true or false
  utf-8-validate: set this to true or false
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - bufferutil
  - core-js
  - esbuild
  - prisma
  - svelte-preprocess
  - utf-8-validate
